[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Translate natural language prompts into function calls using constrained decoding."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy>=2.2.6",
    "pydantic>=2.13.5",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
]
